FROM alpine:3.21.1

# renovate: datasource=github-tags depName=openjdk/jdk17u versioning=regex:^jdk-(?<major>\d+)(?:\.(?<minor>\d+)\.(?<patch>\d+))?\+(?<build>\d+)$
ARG JDK_UPDATES_TAG=jdk-17.0.14+5

# renovate: datasource=github-tags depName=openjdk/jdk17u extractVersion=:^jdk-(?<version>[0-9.+]+)$
ARG JDK_SELF_DESTRUCT="17.0.14+5"
