on:
  workflow_call:
    inputs:
      image_repository:
        type: string
        required: true
      image_tag:
        type: string
        required: true
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo ${{ inputs.image_repository }}:${{ inputs.image_tag }}
