name: CI/CD
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  main:
    uses: ./.github/workflows/docker.yaml
    with:
      image_repository: docker.io/library/java
      image_tag: 17.0.14
