name: CI/CD
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  main:
    uses: ./.github/workflows/docker.yaml
    with:
      image_repository: docker.io/library/java
      # renovate: datasource=github-tags depName=openjdk/jdk17u versioning=semver extractVersion=^jdk-(?<version>[\d.]+)\+\d+$
      image_tag: 17.0.14
