name: CI/CD
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          tags: java:21.0.6
          build-args: |
            jdk_updates_release=https://github.com/openjdk/jdk21u.git
            jdk_updates_tag=jdk-21.0.6+6
