name: Java (Default)
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set build arguments
        id: args
        run: |
          # renovate: datasource=github-tags depName=openjdk/jdk17u versioning=semver extractVersion=^jdk-(?<version>[\d.]+)\+\d+$
          image_tag=17.0.16
          # renovate: datasource=github-tags depName=openjdk/jdk17u versioning=regex:^jdk-(?<major>\d+)\.(?<minor>\d+)\.(?<patch>\d+)\+(?<build>\d+)$
          jdk_version=jdk-17.0.16+7

          echo jdk_version=$jdk_version >> "$GITHUB_OUTPUT"
          echo jdk_updates=https://github.com/openjdk/jdk17u/archive/refs/tags/$jdk_version.tar.gz >> "$GITHUB_OUTPUT"
          echo jdk_release=https://cdn.azul.com/zulu/bin/zulu17.58.21-ca-jdk17.0.15-linux_x64.tar.gz >> "$GITHUB_OUTPUT"

          if [ ${{ github.ref }} == refs/heads/master ]; then
              echo image_tag=$image_tag >> "$GITHUB_OUTPUT"
          else
              echo image_tag=dev >> "$GITHUB_OUTPUT"
          fi
      - name: Build and push
        uses: ./.github/actions/docker
        with:
          repository: docker.io/library/java
          tag: ${{ steps.args.outputs.image_tag }}
          context: .
          arguments: |
            JDK_VERSION=${{ steps.args.outputs.jdk_version }}
            JDK_UPDATES=${{ steps.args.outputs.jdk_updates }}
            JDK_RELEASE=${{ steps.args.outputs.jdk_release }}
